net: enp5s0
num_joints: 29

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

control_dt: 0.02

error_over_time: 5

joint_csv_log:
  enabled: true
  output_dir: "logs/real_joint_angles"
  sample_stride: 1